apiVersion: v1
kind: Service
metadata:
  name: practice-22-backend
spec:
  selector:
    app: practice-22-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
