jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build Service 1
        run: npm run build:app1 
      
      - name: Build Service 2
        run: npm run build:app2 # Предположим, результат в dist/app2
      
      # Важно: загружаем всю папку dist, внутри которой лежат app1 и app2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist' # Загружаем корневую папку со всеми собранными проектами
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4